# Generated by Django 3.0.5 on 2020-04-20 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form_creator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='default_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form_creator.Question'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form_creator.FormTemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='formsubmission',
            unique_together={('form', 'question', 'answered_by')},
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='response',
        ),
    ]
